<script setup>
import {
  IonContent,
  IonPage,
  IonSpinner,
  IonButton,
  IonCol,
  IonRow,
  IonModal,
  IonTextarea,
  useIonRouter,
  onIonViewWillEnter,
} from "@ionic/vue";
import LeavesHeader from "@/components/leaves/Header.vue";
import { useRoute } from "vue-router";
import { computed, ref } from "vue";
import { useUserStore } from "@/store/user";
import shiftsApi from "@/api/shifts.ts";
import { useCustomToast } from "@/composable/toast";
import useDateHelper from "@/composable/useDateHelper";
import dayjs from "dayjs";
import { storeToRefs } from "pinia";
import IconLeave from "@/components/icon/Leave.vue";

const { formatDate } = useDateHelper();
const router = useIonRouter();
const userStore = useUserStore();
const { user } = storeToRefs(userStore);
const { showErrorToast, showSuccessToast } = useCustomToast();
const route = useRoute();

const showAcceptModal = ref(false);
const showRejectModal = ref(false);
const isLoading = ref(false);
const isActionLoading = ref(false);

const triggerBack = () => {
  router.push("/shifts");
};

const shift = ref({});
const editableReason = ref("");

const formatDateToDisplay = (date) => {
  if (!date) return "";
  return dayjs(date, "YYYY-MM-DD").format("DD MMM, YYYY");
};

const fetchShiftDetails = async () => {
  try {
    isLoading.value = true;
    const { data } = await shiftsApi.details({
      shift_request_id: route.params.id,
    });

    if (data && data.status_code === 200) {
      shift.value = data.data || {};
      editableReason.value = shift.value.reason || "";
    }
  } catch (error) {
    showErrorToast(error?.data?.error || "Failed to fetch shift details");
    shift.value = {};
  } finally {
    isLoading.value = false;
  }
};

const rejectShift = async () => {
  try {
    if (!editableReason.value || !editableReason.value.trim()) {
      showErrorToast("Please provide a reason for rejection.");
      showRejectModal.value = false;
      return;
    }

    isActionLoading.value = true;
    await shiftsApi.updateShiftStatus({
      shift_request_id: route.params.id,
      action: "Reject",
      reason: editableReason.value,
    });

    showRejectModal.value = false;
    showSuccessToast("Shift Request rejected successfully");
    fetchShiftDetails(); // Refresh
  } catch (error) {
    showErrorToast(error?.data?.error || "Failed to reject shift request");
  } finally {
    isActionLoading.value = false;
  }
};

const acceptShift = async () => {
  try {
    const defaultReason = `Shift Request Application for ${shift.value.purpose} from ${shift.value.employee_name}`;
    
    if (!editableReason.value || !editableReason.value.trim()) {
      showErrorToast("Reason cannot be blank. Please provide a specific reason.");
      showAcceptModal.value = false;
      return;
    }

    if (editableReason.value === defaultReason) {
      showErrorToast("Autogenerated reason detected! Please provide a more specific reason before approving.");
      showAcceptModal.value = false;
      return;
    }

    isActionLoading.value = true;
    await shiftsApi.updateShiftStatus({
      shift_request_id: route.params.id,
      action: "Approve",
      reason: editableReason.value,
    });

    showAcceptModal.value = false;
    showSuccessToast("Shift Request approved successfully");
    fetchShiftDetails(); // Refresh
  } catch (error) {
    showErrorToast(error?.data?.error || "Failed to approve shift request");
  } finally {
    isActionLoading.value = false;
  }
};

onIonViewWillEnter(async () => {
  await fetchShiftDetails();
});
</script>

<template>
  <ion-page>
    <ion-content class="ion-padding shifts-page">
      <LeavesHeader
        class="shifts-page-header"
        :title="$t('user.shifts.shift_details')"
        @click-back="triggerBack"
      />
      
      <div v-if="isLoading" class="ion-text-center ion-padding">
        <ion-spinner name="crescent"></ion-spinner>
      </div>
      <div v-else class="shifts-details">
        <p class="shifts-details-title">{{ $route.params.id }}</p>

        <div class="shifts-details-card">
          <div class="shifts-details-card-value-wrapper">
            <p class="shifts-details-card-label">
              {{ $t("user.shifts.detail.status") }}
            </p>
            <p
              class="shifts-details-card-value"
              v-if="shift.workflow_state"
              :class="`shifts-status__${shift.workflow_state}`"
            >
              {{ $t(`user.shifts.card.status.${shift.workflow_state?.toLowerCase()}`) || shift.workflow_state }}
            </p>
          </div>

          <div class="shifts-details-card-value-wrapper">
            <p class="shifts-details-card-label">
              {{ $t("user.shifts.detail.employee_name") }}
            </p>
            <p class="shifts-details-card-value">
              {{ shift.employee_name }}
            </p>
          </div>

          <div class="shifts-details-card-value-wrapper">
            <p class="shifts-details-card-label">
              {{ $t("user.shifts.detail.purpose") }}
            </p>
            <p class="shifts-details-card-value">
              {{ shift.purpose ? ($t(`user.shifts.card.purpose.${shift.purpose?.toLowerCase().replaceAll(" ", "_")}`) || shift.purpose) : '' }}
            </p>
          </div>

          <div class="shifts-details-card-value-wrapper">
            <p class="shifts-details-card-label">
              {{ $t("user.shifts.detail.from") }}
            </p>
            <p class="shifts-details-card-value">
              {{ formatDateToDisplay(shift.from_date) }}
            </p>
          </div>

          <div class="shifts-details-card-value-wrapper">
            <p class="shifts-details-card-label">
              {{ $t("user.shifts.detail.to") }}
            </p>
            <p class="shifts-details-card-value">
              {{ formatDateToDisplay(shift.to_date) }}
            </p>
          </div>

          <div class="shifts-details-card-value-wrapper">
            <p class="shifts-details-card-label">
              {{ $t("user.shifts.detail.reason") }}
            </p>
            <div v-if="shift.is_approver && shift.workflow_state === 'Pending Approval'">
              <ion-textarea
                fill="outline"
                v-model="editableReason"
                rows="3"
                class="reason-textarea"
                :placeholder="$t('user.shifts.enter_reason')"
              />
            </div>
            <p v-else class="shifts-details-card-value">
              {{ shift.reason }}
            </p>
          </div>
        </div>

        <ion-row
          class="ion-margin-top"
          v-if="
            shift.workflow_state === 'Pending Approval' &&
            shift.is_approver
          "
        >
          <ion-col>
            <ion-button
              color="danger"
              expand="block"
              shape="round"
              @click="showRejectModal = true"
            >
              Reject
            </ion-button>
          </ion-col>
          <ion-col>
            <ion-button
              color="success"
              expand="block"
              shape="round"
              @click="showAcceptModal = true"
            >
              Approve
            </ion-button>
          </ion-col>
        </ion-row>
      </div>
    </ion-content>

    <ion-modal :is-open="showAcceptModal">
      <div class="leave-confirm-location ion-align-items-center ion-justify-content-center d-flex">
        <div class="leave-confirm-card">
          <div class="leave-confirm-card-icon-wrapper-accept">
            <IconLeave />
          </div>
          <p class="leave-confirm-card-title">
            Approve Shift Request
          </p>
          <p class="leave-confirm-card-description">
            Are you sure you want to approve this shift request?
          </p>
          <ion-row class="ion-justify-content-end">
            <ion-button
              @click="showAcceptModal = false"
              class="leave-confirm-card-back"
              fill="clear"
              :disabled="isActionLoading"
            >
              {{ $t("utils.back") }}
            </ion-button>
            <ion-button fill="clear" color="success" @click="acceptShift">
              <ion-spinner v-if="isActionLoading" name="crescent"></ion-spinner>
              <span v-else>{{ $t("utils.confirm") }}</span>
            </ion-button>
          </ion-row>
        </div>
      </div>
    </ion-modal>

    <ion-modal :is-open="showRejectModal">
      <div class="leave-confirm-location ion-align-items-center ion-justify-content-center d-flex">
        <div class="leave-confirm-card">
          <div class="leave-confirm-card-icon-wrapper-reject">
            <IconLeave />
          </div>
          <p class="leave-confirm-card-title">
            Reject Shift Request
          </p>
          <p class="leave-confirm-card-description">
             Are you sure you want to reject this shift request?
          </p>
          <ion-row class="ion-justify-content-end">
            <ion-button
              @click="showRejectModal = false"
              class="leave-confirm-card-back"
              fill="clear"
              :disabled="isActionLoading"
            >
              {{ $t("utils.back") }}
            </ion-button>
            <ion-button fill="clear" color="danger" @click="rejectShift">
              <ion-spinner v-if="isActionLoading" name="crescent"></ion-spinner>
              <span v-else>{{ $t("utils.confirm") }}</span>
            </ion-button>
          </ion-row>
        </div>
      </div>
    </ion-modal>
  </ion-page>
</template>

<style scoped lang="scss">
.shifts-page {
  --padding-top: 0;
  --padding-bottom: 24px;
  --padding-start: 0;
  --padding-end: 0;

  &-header {
    position: sticky;
    top: 0;
    padding: 0 15px;
    z-index: 1;
    background: #191c1d;
  }
}

.leave-confirm-location {
  height: 100%;
}

.leave-confirm-card {
  margin: 0 20px;
  padding: 18px 16px 10px;
  background: #233036;
  border-radius: 28px;
  width: 100%;

  &-icon-wrapper-reject {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 48px;
    width: 48px;
    margin: 0 auto;
    background: #ffb3ac;
    color: #68000a;
    border-radius: 50%;
  }

  &-icon-wrapper-accept {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 48px;
    width: 48px;
    margin: 0 auto;
    background: #52e169;
    color: #00390c;
    border-radius: 50%;
  }

  &-title {
    text-align: center;
    font-size: 1.5rem;
    line-height: 2rem;
    color: #e0e3e3;
    margin-top: 16px;
  }

  &-description {
    font-size: 0.925rem;
    line-height: 1.25rem;
    color: #c0c7cd;
    text-align: center;
    margin: 16px 0;
  }

  &-back {
    color: #c0c7cd;
  }
}

.d-flex {
  display: flex !important;
}

.shifts-details {
  padding: 16px;

  &-title {
    font-size: 0.875rem;
    line-height: 1.25rem;
    font-weight: 500;
    margin: 0 6px 16px;
  }

  &-card {
    padding: 24px 16px;
    border-radius: 16px;
    background: #1e2529;

    &-label {
      margin: 0;
      font-size: 0.875rem;
      line-height: 1.25rem;
      color: #8b9298;
    }

    &-value {
      margin: 4px 0 4px;
      font-size: 1rem;
      line-height: 1.5rem;
      color: #e0e3e3;
    }

    &-value-wrapper {
      &:not(:first-child) {
        margin-top: 16px;
      }
    }
  }
}

.shifts-status__Draft, .shifts-status__Open {
  color: #76d1ff;
}
.shifts-status__Approved {
  color: #52e169;
}
.shifts-status__Rejected {
  color: #ffb4a9;
}
.shifts-status__Cancelled {
  color: #8b9298;
}

.reason-textarea {
  margin-top: 8px;
  --background: #233036;
  --color: #e0e3e3;
  --padding-start: 12px;
  --padding-end: 12px;
  --padding-top: 12px;
  --padding-bottom: 12px;
  border-radius: 8px;
  font-size: 0.95rem;
}
</style>
