name: Build Apk

on:
  push:
    branches:
      - pipeline

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Ionic
        run: npm install -g @ionic/cli

      - name: Install app dependencies
        run: npm install

      - name: Build Ionic App
        run: npm run build

      - name: Copy Android
        run: ionic capacitor sync

      - name: Build Android Dev APK
        run: ionic capacitor build android

      - name: Build Android Release APK
        run: ionic capacitor build android --release --prod

      - name: Generate the Android App Bundle
        working-directory: ./android/
        run: ./gradlew assembleDebug

      - name: Upload dev APK
        uses: actions/upload-artifact@v4
        with:
          name: app-dev
          path: android/app/build/outputs/apk/debug/app-debug.apk

